normalized indent to tab

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -15,26 +15,26 @@ fi
 
 # If missing, download and extract the dotfiles repository
 if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
-    printf "Initializing directory ${DOTFILES_DIRECTORY}..."
+	printf "Initializing directory ${DOTFILES_DIRECTORY}..."
 
-	tmpfile="${TMPDIR:-${TEMP:-/tmp}}/$(mktemp -u XXXXX.tgz)"
+	tmpfile="${TMPDIR:-${TEMP:-/tmp}}/dotfiles.tgz"
 
-    mkdir "${DOTFILES_DIRECTORY}" || exit
+	mkdir "${DOTFILES_DIRECTORY}" || exit
 	curl -fsSLo "${tmpfile}" ${DOTFILES_GIT_TARBALL} || exit
-    tar -zxf "${tmpfile}" --strip-components 1 -C "${DOTFILES_DIRECTORY}" #no exit
-    rm -f "${tmpfile}"
+	tar -zxf "${tmpfile}" --strip-components 1 -C "${DOTFILES_DIRECTORY}"
+	rm -f "${tmpfile}"
 
-    if [ ! -x "${DOTFILES_DIRECTORY}/bin/dotfiles" ]; then
-    	printf "FAILED\n"
-    	exit
-    fi
-    printf "done\n"
-    unset tmpfile
+	if [ ! -x "${DOTFILES_DIRECTORY}/bin/dotfiles" ]; then
+		printf "FAILED\n"
+		exit
+	fi
+	printf "done\n"
+	unset tmpfile
 fi
 
 # Load the library functions
 cd ${DOTFILES_DIRECTORY}
-for f in ./lib/*; do 
+for f in ./lib/*; do
 	source $f || exit
 done
 
@@ -42,18 +42,18 @@ done
 is_dry_run=false
 dry_run=;
 for opt in $@; do
-    case $opt in
-    	--dry-run) 
-			is_dry_run=true 
+	case $opt in
+		--dry-run)
+			is_dry_run=true
 			dry_run=log_dryrun
 			;;
-        --no-modules) no_modules=true ;;
-        --no-packages) no_packages=true ;;
+		--no-modules) no_modules=true ;;
+		--no-packages) no_packages=true ;;
 		--no-link) no_link=true ;;
-        --no-sync) no_sync=true ;;
+		--no-sync) no_sync=true ;;
 		-h|--help) run_help ;;
-        -*|--*) e_warning "Warning: invalid option $opt" ;;
-    esac
+		-*|--*) e_warning "Warning: invalid option $opt" ;;
+	esac
 done
 
 # Set the $os and $distro variables
@@ -63,9 +63,9 @@ setup_os
 check_sudo
 
 if have_gitconfig; then
-  read_gitconfig
+	read_gitconfig
 else
-  prompt_gitconfig
+	prompt_gitconfig
 fi
 
 log_header "Prerequsites"
@@ -94,7 +94,7 @@ fi
 if [[ ! $no_link ]]; then
 	log_header "Linking"
 	run_link
-  write_gitconfig
+	write_gitconfig
 fi
 
 log_summary
diff --git a/lib/git b/lib/git
--- a/lib/git
+++ b/lib/git
@@ -3,23 +3,23 @@
 # Confirm ssh key setup on GitHub
 check_github_ssh() {
 		if ! github_check_key; then
-		    $dry_run ssh_copy_key \
-		    	&& log_success "SSH key copied to clipboard" \
-		    	|| log_fatal "Failed to copy key"
-		    
+			$dry_run ssh_copy_key \
+				&& log_success "SSH key copied to clipboard" \
+				|| log_fatal "Failed to copy key"
 
-		    if [[ $os == "osx" ]]; then
-			    $dry_run open "https://github.com/settings/ssh"
+
+			if [[ $os == "osx" ]]; then
+				$dry_run open "https://github.com/settings/ssh"
 			fi
 
-		    while :
-		    do
-		    	ask_anykey
-		      github_check_key \
-		      	&& break \
-		      	|| log_warning "GitHub SSH still not working"
-		    done
-		fi	
+			while :
+			do
+				ask_anykey
+				github_check_key \
+					&& break \
+					|| log_warning "GitHub SSH still not working"
+			done
+		fi
 		log_success "GitHub SSH working"
 }
 
@@ -28,12 +28,12 @@ check_git() {
 		log_success "Git found"
 	else
 		case $os in
-      		osx*)
+			osx*)
 				log_step "Installing git..."
 				$dry_run brew install git \
 					&& log_success "Installed git" \
 					|| log_fatal "Failed to install git"
-		        ;;
+				;;
 			*)
 				log_fatal "Unable to install git"
 				;;
@@ -46,43 +46,43 @@ check_git_repo() {
 		log_success "Is a git repository"
 	else
 		log_step "Initializing repository..."
-	    $dry_run git init \
-	    	|| log_fatal "Failed to initialize repository"
+		$dry_run git init \
+			|| log_fatal "Failed to initialize repository"
 
 		log_step "Adding remote..."
-	    $dry_run git remote add origin ${DOTFILES_GIT_REMOTE} \
-	    	|| log_fatal "Failed to add remote"
+		$dry_run git remote add origin ${DOTFILES_GIT_REMOTE} \
+			|| log_fatal "Failed to add remote"
 
-	    log_step "Fetching origin..."
-	    $dry_run git fetch origin master \
-	    	|| log_fatal "Failed to fetch origin"
+		log_step "Fetching origin..."
+		$dry_run git fetch origin master \
+			|| log_fatal "Failed to fetch origin"
 
-	    log_step "Resetting working tree..."
-	    $dry_run git reset --hard FETCH_HEAD \
-	    	|| log_fatal "Failed to reset to HEAD"
+		log_step "Resetting working tree..."
+		$dry_run git reset --hard FETCH_HEAD \
+			|| log_fatal "Failed to reset to HEAD"
 
-	    # log_step "Cleaning..."
-	    # $dry_run git clean -fd \
-	    # 	|| log_warning "Failed to clean git clone"
+		log_step "Cleaning..."
+		$dry_run git clean -fd \
+			|| log_warning "Failed to clean git clone"
 
-	    log_step "Double checking clone..."
-	    $dry_run is_git_repo \
-	    	&& log_success "Repository initialized" \
-	    	|| log_fatal "Failed to initialize git repository"
+		log_step "Double checking clone..."
+		$dry_run is_git_repo \
+			&& log_success "Repository initialized" \
+			|| log_fatal "Failed to initialize git repository"
 	fi
 }
 
 # Test whether we're in a git repo
 is_git_repo() {
-  git rev-parse --is-inside-work-tree &> /dev/null || return 1
+	git rev-parse --is-inside-work-tree &> /dev/null || return 1
 	return 0
 }
 
 # Test the default SSH key against github
 github_check_key() {
-		local tmp=$(ssh -T git@github.com 2>&1)
-    [[  $tmp =~ "successfully authenticated" ]] || return 1
-    return 0
+	local tmp=$(ssh -T git@github.com 2>&1)
+	[[  $tmp =~ "successfully authenticated" ]] || return 1
+	return 0
 }
 
 # sync repository
@@ -100,14 +100,14 @@ git_sync() {
 		|| log_success "Global gitconfig unchanged"
 
 	log_step "Pulling from origin..."
-    $dry_run git pull --rebase origin master \
+	$dry_run git pull --rebase origin master \
 		&& log_success "Origin fetched and rebased" \
 		|| log_error "Failed to rebase from origin"
 
 	log_step "Updating submodules..."
-    $dry_run git submodule update --recursive --init --quiet \
-    	&& log_success "Submodules updated" \
-    	|| log_error "Failed to update submodules"
+	$dry_run git submodule update --recursive --init --quiet \
+		&& log_success "Submodules updated" \
+		|| log_error "Failed to update submodules"
 }
 
 have_gitconfig() {
@@ -122,7 +122,7 @@ read_gitconfig() {
 
 prompt_gitconfig() {
 	log_info "Provide git name and email for SSH key creation and GitHub access"
-	
+
 	ask "Name"
 	git_name=$(get_answer)
 
diff --git a/lib/ssh b/lib/ssh
--- a/lib/ssh
+++ b/lib/ssh
@@ -4,32 +4,32 @@ ssh_key_file="${HOME}/.ssh/id_rsa"
 
 # Check if SSH key exists, if not create it
 check_ssh() {
-    if ssh_key_exists; then
-        log_success "SSH key found"
-    else
-        ask_confirmation "SSH key not found, would you like to set one up?"
-        is_confirmed || log_fatal "SSH key required"
-        ssh_create_key || log_fatal "Failed to create ssh key"
-        $dry_run ssh_key_exists \
-            && log_success "SSH key generated" \
-            || log_fatal "Generated SSH key not found"
-    fi
+	if ssh_key_exists; then
+		log_success "SSH key found"
+	else
+		ask_confirmation "SSH key not found, would you like to set one up?"
+		is_confirmed || log_fatal "SSH key required"
+		ssh_create_key || log_fatal "Failed to create ssh key"
+		$dry_run ssh_key_exists \
+			&& log_success "SSH key generated" \
+			|| log_fatal "Generated SSH key not found"
+	fi
 }
 
 ssh_key_exists() {
-    [[ -r "$ssh_key_file" ]] || return 1
-    return 0
+	[[ -r "$ssh_key_file" ]] || return 1
+	return 0
 }
 
 # Setup SSH Key
 # https://help.github.com/articles/generating-ssh-keys
 ssh_create_key() {
-    $dry_run ssh-keygen -t rsa -C "${git_email}" -f "${ssh_key_file}"
+	$dry_run ssh-keygen -t rsa -C "${git_email}" -f "${ssh_key_file}"
 }
 
 ssh_copy_key() {
-    case $os in
-        osx) cat "$ssh_key_file.pub" | pbcopy ;;
-        *) ;; #todo
-    esac
+	case $os in
+		osx) cat "$ssh_key_file.pub" | pbcopy ;;
+		*) ;; #todo
+	esac
 }
diff --git a/lib/sys b/lib/sys
--- a/lib/sys
+++ b/lib/sys
@@ -1,85 +1,85 @@
 #!/usr/bin/env bash
 
 check_package_manager() {
-    case $os in
-        osx*) check_brew ;;
-        *) ;; #todo
-    esac
+	case $os in
+		osx*) check_brew ;;
+		*) ;; #todo
+	esac
 }
 
 check_build_tools() {
-    case $os in
-        osx*) check_xcode ;;
-        *) ;; #todo
-    esac
+	case $os in
+		osx*) check_xcode ;;
+		*) ;; #todo
+	esac
 }
 
 run_packages() {
-    case $os in
-        osx*) run_brew ;;
-        *) ;; #todo
-    esac
+	case $os in
+		osx*) run_brew ;;
+		*) ;; #todo
+	esac
 }
 
 check_sudo() {
-    local need_sudo=false
-    case $io in
-        osx)
-            [[ ! is_xcode_installed || ! is_brew_installed ]] || need_sudo=true
-            ;;
-        *) ;; #todo
-    esac
+	local need_sudo=false
+	case $io in
+		osx)
+			[[ ! is_xcode_installed || ! is_brew_installed ]] || need_sudo=true
+			;;
+		*) ;; #todo
+	esac
 
-    # Ask for the administrator password upfront and keep-alive until finished
-    # NOTE: installing homebrew will invalidate the keep-alive :(
-    if $need_sudo; then
-        log_info "This system requires sudo for some operations"
-        sudo -k # invalidate any existing sudo
-        sudo -v # prompt for password
-        while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
-    fi
+	# Ask for the administrator password upfront and keep-alive until finished
+	# NOTE: installing homebrew will invalidate the keep-alive :(
+	if $need_sudo; then
+		log_info "This system requires sudo for some operations"
+		sudo -k # invalidate any existing sudo
+		sudo -v # prompt for password
+		while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+	fi
 }
 
 # Test whether a command exists
 # $1 - cmd to test
 # - https://github.com/necolas/dotfiles
 type_exists() {
-    if [ $(type -P $1) ]; then
-      return 0
-    fi
-    return 1
+	if [ $(type -P $1) ]; then
+		return 0
+	fi
+	return 1
 }
 
 # Setup the $os and $distro
 # See: http://linuxmafia.com/faq/Admin/release-files.html
 setup_os() {
-    case $OSTYPE in
-      darwin*)
-        os="osx"
-        if [ $(compare_versions "$(sw_vers -productVersion)" "10.9") == '<' ]; then
-            log_error "OS X 10.9.0+ required"
-            return 1
-        fi
-        ;;
-      linux*)
-        os="linux"
-        if [[ -e "/etc/lsb-release" ]]; then
-            distro="ubuntu" 
-        elif [[ -e "/etc/debian_release" || -e "/etc/debian_version" ]]; then
-            distro="debian"
-        elif [[ -e "/etc/redhat-release" || -e "/etc/redhat-version" ]]; then
-            distro="redhat"
-        elif [[ -e "/etc/fedora-release" ]]; then
-            distro="fedora"
-        else
-            log_error "Unsupported linux distro"
-            return 1
-        fi
-        ;;
-      *)
-        log_error "Unsupported OS"
-        return 1
-        ;;
-    esac
-    return 0
+	case $OSTYPE in
+		darwin*)
+			os="osx"
+			if [ $(compare_versions "$(sw_vers -productVersion)" "10.9") == '<' ]; then
+				log_error "OS X 10.9.0+ required"
+				return 1
+			fi
+			;;
+		linux*)
+			os="linux"
+			if [[ -e "/etc/lsb-release" ]]; then
+				distro="ubuntu"
+			elif [[ -e "/etc/debian_release" || -e "/etc/debian_version" ]]; then
+				distro="debian"
+			elif [[ -e "/etc/redhat-release" || -e "/etc/redhat-version" ]]; then
+				distro="redhat"
+			elif [[ -e "/etc/fedora-release" ]]; then
+				distro="fedora"
+			else
+				log_error "Unsupported linux distro"
+				return 1
+			fi
+			;;
+		*)
+			log_error "Unsupported OS"
+			return 1
+			;;
+	esac
+	return 0
 }
