oops, indent with spaces

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -9,51 +9,51 @@ DOTFILES_GIT_REMOTE="git@github.com:${DOTFILES_REPOSITORY}.git"
 
 # Ensure not running as root
 if [ $EUID == 0 ]; then
-	echo "Do not run as root. Aborting."
-	exit
+    echo "Do not run as root. Aborting."
+    exit
 fi
 
 # If missing, download and extract the dotfiles repository
 if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
-	printf "Initializing directory ${DOTFILES_DIRECTORY}..."
+    printf "Initializing directory ${DOTFILES_DIRECTORY}..."
 
-	tmpfile="${TMPDIR:-${TEMP:-/tmp}}/dotfiles.tgz"
+    tmpfile="${TMPDIR:-${TEMP:-/tmp}}/dotfiles.tgz"
 
-	mkdir "${DOTFILES_DIRECTORY}" || exit
-	curl -fsSLo "${tmpfile}" ${DOTFILES_GIT_TARBALL} || exit
-	tar -zxf "${tmpfile}" --strip-components 1 -C "${DOTFILES_DIRECTORY}"
-	rm -f "${tmpfile}"
+    mkdir "${DOTFILES_DIRECTORY}" || exit
+    curl -fsSLo "${tmpfile}" ${DOTFILES_GIT_TARBALL} || exit
+    tar -zxf "${tmpfile}" --strip-components 1 -C "${DOTFILES_DIRECTORY}"
+    rm -f "${tmpfile}"
 
-	if [ ! -x "${DOTFILES_DIRECTORY}/bin/dotfiles" ]; then
-		printf "FAILED\n"
-		exit
-	fi
-	printf "done\n"
-	unset tmpfile
+    if [ ! -x "${DOTFILES_DIRECTORY}/bin/dotfiles" ]; then
+        printf "FAILED\n"
+        exit
+    fi
+    printf "done\n"
+    unset tmpfile
 fi
 
 # Load the library functions
 cd ${DOTFILES_DIRECTORY}
 for f in ./lib/*; do
-	source $f || exit
+    source $f || exit
 done
 
 # Parse command line options
 is_dry_run=false
 dry_run=;
 for opt in $@; do
-	case $opt in
-		--dry-run)
-			is_dry_run=true
-			dry_run=log_dryrun
-			;;
-		--no-modules) no_modules=true ;;
-		--no-packages) no_packages=true ;;
-		--no-link) no_link=true ;;
-		--no-sync) no_sync=true ;;
-		-h|--help) run_help ;;
-		-*|--*) e_warning "Warning: invalid option $opt" ;;
-	esac
+    case $opt in
+        --dry-run)
+            is_dry_run=true
+            dry_run=log_dryrun
+            ;;
+        --no-modules) no_modules=true ;;
+        --no-packages) no_packages=true ;;
+        --no-link) no_link=true ;;
+        --no-sync) no_sync=true ;;
+        -h|--help) run_help ;;
+        -*|--*) e_warning "Warning: invalid option $opt" ;;
+    esac
 done
 
 # Set the $os and $distro variables
@@ -63,9 +63,9 @@ setup_os
 check_sudo
 
 if have_gitconfig; then
-	read_gitconfig
+    read_gitconfig
 else
-	prompt_gitconfig
+    prompt_gitconfig
 fi
 
 log_header "Prerequsites"
@@ -77,24 +77,24 @@ check_git
 check_git_repo
 
 if [[ ! $no_sync ]]; then
-	log_header "Synchronizing repository"
-	git_sync
+    log_header "Synchronizing repository"
+    git_sync
 fi
 
 if [[ ! $no_packages ]]; then
-	log_header "Install Packages"
-	run_packages
+    log_header "Install Packages"
+    run_packages
 fi
 
 if [[ ! $no_modules ]]; then
-	log_header "Install Modules"
-	run_npm
+    log_header "Install Modules"
+    run_npm
 fi
 
 if [[ ! $no_link ]]; then
-	log_header "Linking"
-	run_link
-	write_gitconfig
+    log_header "Linking"
+    run_link
+    write_gitconfig
 fi
 
 log_summary
diff --git a/lib/brew b/lib/brew
--- a/lib/brew
+++ b/lib/brew
@@ -1,96 +1,96 @@
 #!/usr/bin/env bash
 
 declare -a brew_taps=(
-	'caskroom/cask'
-	'homebrew/dupes'
-	'homebrew/versions'
+    'caskroom/cask'
+    'homebrew/dupes'
+    'homebrew/versions'
 )
 
 declare -a brew_formulae=(
-	'coreutils'
-	'git'
-	'bash'
-	'bash-completion'
-	'node'
-	'tree'
-	'wget'
-	'jq'
-	'openssl'
-	'brew-cask'
-	'homebrew/dupes/rsync'
+    'coreutils'
+    'git'
+    'bash'
+    'bash-completion'
+    'node'
+    'tree'
+    'wget'
+    'jq'
+    'openssl'
+    'brew-cask'
+    'homebrew/dupes/rsync'
 )
 
 check_brew() {
-	if type_exists 'brew'; then
-		log_success "Homebrew found"
-	else
-		# no redirect here since homebrew will ask for sudu
-		log_info "Installing Homebrew..."
-		$dry_run ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" \
-			&& log_success "Homebrew installed" \
-			|| log_fatal "Failed to install homebrew"
+    if type_exists 'brew'; then
+        log_success "Homebrew found"
+    else
+        # no redirect here since homebrew will ask for sudu
+        log_info "Installing Homebrew..."
+        $dry_run ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" \
+            && log_success "Homebrew installed" \
+            || log_fatal "Failed to install homebrew"
 
-		log_step "Checking brew path..."
-		$dry_run type_exists 'brew' \
-			&& log_success "Brew in PATH" \
-			|| log_fatal "Failed to find brew command"
+        log_step "Checking brew path..."
+        $dry_run type_exists 'brew' \
+            && log_success "Brew in PATH" \
+            || log_fatal "Failed to find brew command"
 
-		log_step "Running brew doctor..."
-		$dry_run brew doctor \
-			&& log_success "Ready to brew" \
-			|| log_warning "Brew doctor failed"
+        log_step "Running brew doctor..."
+        $dry_run brew doctor \
+            && log_success "Ready to brew" \
+            || log_warning "Brew doctor failed"
 
-		log_step "Running brew update"
-		$dry_run brew update \
-			&& log_success "Brew updated" \
-			|| log_warning "Brew update failed"
-	fi
+        log_step "Running brew update"
+        $dry_run brew update \
+            && log_success "Brew updated" \
+            || log_warning "Brew update failed"
+    fi
 }
 
 run_brew() {
-	type_exists 'brew' || log_fatal "Homebrew not found"
+    type_exists 'brew' || log_fatal "Homebrew not found"
 
-	log_info "Updating taps..."
-	local -a installed_taps=($(brew tap))
-	local installed=" ${installed_taps[*]} "
-	for item in ${brew_taps[@]}; do
-		if [[ $installed =~ " $item " ]]; then
-			log_neutral "$item"
-		else
-			log_step "Tapping $item..."
-			$dry_run brew tap "$item" \
-				&& log_success "Tapped $item" \
-				|| log_error "Failed to tap $item"
-		fi
-	done
+    log_info "Updating taps..."
+    local -a installed_taps=($(brew tap))
+    local installed=" ${installed_taps[*]} "
+    for item in ${brew_taps[@]}; do
+        if [[ $installed =~ " $item " ]]; then
+            log_neutral "$item"
+        else
+            log_step "Tapping $item..."
+            $dry_run brew tap "$item" \
+                && log_success "Tapped $item" \
+                || log_error "Failed to tap $item"
+        fi
+    done
 
-	log_info "Updating formulae..."
-	$dry_run brew update \
-		&& log_success "Homebrew updated" \
-		|| log_warning "Failed to update Homebrew"
+    log_info "Updating formulae..."
+    $dry_run brew update \
+        && log_success "Homebrew updated" \
+        || log_warning "Failed to update Homebrew"
 
-	log_info "Installing formulae..."
-	for index in ${!brew_formulae[*]}
-	do
-		if formula_exists ${brew_formulae[$index]}; then
-			log_neutral "${brew_formulae[$index]}"
-		else
-			log_step "Brewing ${brew_formulae[$index]}..."
-			$dry_run brew install "${brew_formulae[$index]}" \
-				&& log_success "${brew_formulae[$index]}" \
-				|| log_error "${brew_formulae[$index]}"
-		fi
-	done
+    log_info "Installing formulae..."
+    for index in ${!brew_formulae[*]}
+    do
+        if formula_exists ${brew_formulae[$index]}; then
+            log_neutral "${brew_formulae[$index]}"
+        else
+            log_step "Brewing ${brew_formulae[$index]}..."
+            $dry_run brew install "${brew_formulae[$index]}" \
+                && log_success "${brew_formulae[$index]}" \
+                || log_error "${brew_formulae[$index]}"
+        fi
+    done
 
-	log_info "Cleaning outdated formulae..."
-	$dry_run brew cleanup \
-		&& log_success "Formulae cleaned" \
-		|| log_warning "Failed to clean formulae"
+    log_info "Cleaning outdated formulae..."
+    $dry_run brew cleanup \
+        && log_success "Formulae cleaned" \
+        || log_warning "Failed to clean formulae"
 }
 
 # Test whether a Homebrew formula is already installed
 # $1 - formula name (may include options)
 formula_exists() {
-	[[ -n $(brew list $1) ]] || return 1
-	return 0
+    [[ -n $(brew list $1) ]] || return 1
+    return 0
 }
diff --git a/lib/git b/lib/git
--- a/lib/git
+++ b/lib/git
@@ -2,163 +2,163 @@
 
 # Confirm ssh key setup on GitHub
 check_github_ssh() {
-		if ! github_check_key; then
-			$dry_run ssh_copy_key \
-				&& log_success "SSH key copied to clipboard" \
-				|| log_fatal "Failed to copy key"
+        if ! github_check_key; then
+            $dry_run ssh_copy_key \
+                && log_success "SSH key copied to clipboard" \
+                || log_fatal "Failed to copy key"
 
 
-			if [[ $os == "osx" ]]; then
-				$dry_run open "https://github.com/settings/ssh"
-			fi
+            if [[ $os == "osx" ]]; then
+                $dry_run open "https://github.com/settings/ssh"
+            fi
 
-			while :
-			do
-				ask_anykey
-				github_check_key \
-					&& break \
-					|| log_warning "GitHub SSH still not working"
-			done
-		fi
-		log_success "GitHub SSH working"
+            while :
+            do
+                ask_anykey
+                github_check_key \
+                    && break \
+                    || log_warning "GitHub SSH still not working"
+            done
+        fi
+        log_success "GitHub SSH working"
 }
 
 check_git() {
-	if type_exists 'git'; then
-		log_success "Git found"
-	else
-		case $os in
-			osx*)
-				log_step "Installing git..."
-				$dry_run brew install git \
-					&& log_success "Installed git" \
-					|| log_fatal "Failed to install git"
-				;;
-			*)
-				log_fatal "Unable to install git"
-				;;
-		esac
-	fi
+    if type_exists 'git'; then
+        log_success "Git found"
+    else
+        case $os in
+            osx*)
+                log_step "Installing git..."
+                $dry_run brew install git \
+                    && log_success "Installed git" \
+                    || log_fatal "Failed to install git"
+                ;;
+            *)
+                log_fatal "Unable to install git"
+                ;;
+        esac
+    fi
 }
 
 check_git_repo() {
-	if is_git_repo; then
-		log_success "Is a git repository"
-	else
-		log_step "Initializing repository..."
-		$dry_run git init \
-			|| log_fatal "Failed to initialize repository"
+    if is_git_repo; then
+        log_success "Is a git repository"
+    else
+        log_step "Initializing repository..."
+        $dry_run git init \
+            || log_fatal "Failed to initialize repository"
 
-		log_step "Adding remote..."
-		$dry_run git remote add origin ${DOTFILES_GIT_REMOTE} \
-			|| log_fatal "Failed to add remote"
+        log_step "Adding remote..."
+        $dry_run git remote add origin ${DOTFILES_GIT_REMOTE} \
+            || log_fatal "Failed to add remote"
 
-		log_step "Fetching origin..."
-		$dry_run git fetch origin master \
-			|| log_fatal "Failed to fetch origin"
+        log_step "Fetching origin..."
+        $dry_run git fetch origin master \
+            || log_fatal "Failed to fetch origin"
 
-		log_step "Resetting working tree..."
-		$dry_run git reset --hard FETCH_HEAD \
-			|| log_fatal "Failed to reset to HEAD"
+        log_step "Resetting working tree..."
+        $dry_run git reset --hard FETCH_HEAD \
+            || log_fatal "Failed to reset to HEAD"
 
-		log_step "Cleaning..."
-		$dry_run git clean -fd \
-			|| log_warning "Failed to clean git clone"
+        log_step "Cleaning..."
+        $dry_run git clean -fd \
+            || log_warning "Failed to clean git clone"
 
-		log_step "Double checking clone..."
-		$dry_run is_git_repo \
-			&& log_success "Repository initialized" \
-			|| log_fatal "Failed to initialize git repository"
-	fi
+        log_step "Double checking clone..."
+        $dry_run is_git_repo \
+            && log_success "Repository initialized" \
+            || log_fatal "Failed to initialize git repository"
+    fi
 }
 
 # Test whether we're in a git repo
 is_git_repo() {
-	git rev-parse --is-inside-work-tree &> /dev/null || return 1
-	return 0
+    git rev-parse --is-inside-work-tree &> /dev/null || return 1
+    return 0
 }
 
 # Test the default SSH key against github
 github_check_key() {
-	local tmp=$(ssh -T git@github.com 2>&1)
-	[[  $tmp =~ "successfully authenticated" ]] || return 1
-	return 0
+    local tmp=$(ssh -T git@github.com 2>&1)
+    [[  $tmp =~ "successfully authenticated" ]] || return 1
+    return 0
 }
 
 # sync repository
 git_sync() {
-	# Should probably use plumbing command(s) here, but this works
-	# See: http://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes
-	log_step "Checking for uncommited changes..."
-	[[ -z $(git status -s) ]] \
-		&& log_success "Working directory clean" \
-		|| log_fatal "Uncommited changes found, please commit or stash them"
+    # Should probably use plumbing command(s) here, but this works
+    # See: http://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes
+    log_step "Checking for uncommited changes..."
+    [[ -z $(git status -s) ]] \
+        && log_success "Working directory clean" \
+        || log_fatal "Uncommited changes found, please commit or stash them"
 
-	log_step "Checking gitconfig..."
-	is_gitconfig_changed \
-		&& log_fatal "Global changes to gitconfig not in dotfiles repository" \
-		|| log_success "Global gitconfig unchanged"
+    log_step "Checking gitconfig..."
+    is_gitconfig_changed \
+        && log_fatal "Global changes to gitconfig not in dotfiles repository" \
+        || log_success "Global gitconfig unchanged"
 
-	log_step "Pulling from origin..."
-	$dry_run git pull --rebase origin master \
-		&& log_success "Origin fetched and rebased" \
-		|| log_error "Failed to rebase from origin"
+    log_step "Pulling from origin..."
+    $dry_run git pull --rebase origin master \
+        && log_success "Origin fetched and rebased" \
+        || log_error "Failed to rebase from origin"
 
-	log_step "Updating submodules..."
-	$dry_run git submodule update --recursive --init --quiet \
-		&& log_success "Submodules updated" \
-		|| log_error "Failed to update submodules"
+    log_step "Updating submodules..."
+    $dry_run git submodule update --recursive --init --quiet \
+        && log_success "Submodules updated" \
+        || log_error "Failed to update submodules"
 }
 
 have_gitconfig() {
-	[[ -r "${HOME}/.gitconfig" ]] || return 1
-	return 0
+    [[ -r "${HOME}/.gitconfig" ]] || return 1
+    return 0
 }
 
 read_gitconfig() {
-	git_name=$(git config --global user.name)
-	git_email=$(git config --global user.email)
+    git_name=$(git config --global user.name)
+    git_email=$(git config --global user.email)
 }
 
 prompt_gitconfig() {
-	log_info "Provide git name and email for SSH key creation and GitHub access"
+    log_info "Provide git name and email for SSH key creation and GitHub access"
 
-	ask "Name"
-	git_name=$(get_answer)
+    ask "Name"
+    git_name=$(get_answer)
 
-	ask "Email"
-	git_email=$(get_answer)
+    ask "Email"
+    git_email=$(get_answer)
 }
 
 write_gitconfig() {
-	[[ -e "${HOME}/.gitconfig" ]] && $dry_run mv -f "${HOME}/.gitconfig" "${HOME}/.gitconfig.bak"
+    [[ -e "${HOME}/.gitconfig" ]] && $dry_run mv -f "${HOME}/.gitconfig" "${HOME}/.gitconfig.bak"
 
-	local src="./git/gitconfig-${distro}"
-	[[ -e "$src" ]] || src="./git/gitconfig-$os"
+    local src="./git/gitconfig-${distro}"
+    [[ -e "$src" ]] || src="./git/gitconfig-$os"
 
-	$dry_run cp -f "${src}" "${HOME}/.gitconfig"
-	$dry_run git config --global user.name "${git_name}"
-	$dry_run git config --global user.email "${git_email}"
+    $dry_run cp -f "${src}" "${HOME}/.gitconfig"
+    $dry_run git config --global user.name "${git_name}"
+    $dry_run git config --global user.email "${git_email}"
 
-	log_success "gitconfig updated"
+    log_success "gitconfig updated"
 }
 
 is_gitconfig_changed() {
-	local src="./git/gitconfig-${distro}"
-	[[ -e "$src" ]] || src="./git/gitconfig-$os"
+    local src="./git/gitconfig-${distro}"
+    [[ -e "$src" ]] || src="./git/gitconfig-$os"
 
-	local cur="/tmp/gitconfig.cur"
-	local new="/tmp/gitconfig.new"
+    local cur="/tmp/gitconfig.cur"
+    local new="/tmp/gitconfig.new"
 
-	cat "${HOME}/.gitconfig" | egrep -v "(\[user\]|name = |email = )" >$cur
-	cat "${src}" | egrep -v "(\[user\]|name = |email = )" >$new
+    cat "${HOME}/.gitconfig" | egrep -v "(\[user\]|name = |email = )" >$cur
+    cat "${src}" | egrep -v "(\[user\]|name = |email = )" >$new
 
-	local diff=false
-	diff -B "${cur}" "${new}" || diff=true
+    local diff=false
+    diff -B "${cur}" "${new}" || diff=true
 
-	rm -f "${cur}" "${new}"
+    rm -f "${cur}" "${new}"
 
-	$diff || return 1
-	return 0
+    $diff || return 1
+    return 0
 }
 
diff --git a/lib/xcode b/lib/xcode
--- a/lib/xcode
+++ b/lib/xcode
@@ -1,21 +1,21 @@
 #!/usr/bin/env bash
 
 check_xcode() {
-	if is_xcode_installed; then
-		log_success "Found XCode Command Line Tools"
-	else
-		log_info "Installing XCode Command Line Tools via GUI popup"
-		$dry_run sudo /usr/bin/xcode-select --install
-		$dry_run ask_anykey
-		$dry_run is_xcode_installed \
-			&& log_success "XCode Command Line Tools installed" \
-			|| log_fatal "Failed to install XCode Command Line Tools"
-	fi
+    if is_xcode_installed; then
+        log_success "Found XCode Command Line Tools"
+    else
+        log_info "Installing XCode Command Line Tools via GUI popup"
+        $dry_run sudo /usr/bin/xcode-select --install
+        $dry_run ask_anykey
+        $dry_run is_xcode_installed \
+            && log_success "XCode Command Line Tools installed" \
+            || log_fatal "Failed to install XCode Command Line Tools"
+    fi
 }
 
 is_xcode_installed() {
-	/usr/bin/xcode-select -p &>/dev/null || return 1
-	return 0
+    /usr/bin/xcode-select -p &>/dev/null || return 1
+    return 0
 }
 
 
