really don't run npm if it isn't installed

diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -9,7 +9,10 @@ declare -a npm_modules=(
 )
 
 run_npm() {
-    type_exists 'npm' || log_warning "npm not found"
+    if ! type_exists 'npm'; then
+        log_warning "npm not found"
+        exit
+    fi
 
     log_info "Installing npm modules..."
     local installed=$(npm list --global --depth=0 2> /dev/null)
